### ISSUE TITLE
GPL License?? 😕

### ISSUE THREAD

**Issue by sajattack** [pspdev/vfpu-docs#1]
I'm not sure if a yaml file even can be licensed under GPL since GPL makes different claims about sources and binaries. Especially one that makes use of unlicensed public documentation. But IANAL. Requesting a relicense or license exception for usage in rust-psp. 

https://github.com/overdrivenpotato/rust-psp/pull/160

**Comment by davidgfnet** [comment]
Is there a better license we could use?
Most of the code is autogenerated (some it's not), for that, since it's mostly tests (no libraries) I think GPL is good. I do not expect anyone using any of that code in a game/library. For the YAML, and any other documentation... any license would be good. But IANAL :D so I have no idea what the best license would be.

**Comment by sajattack** [comment]
MIT/Apache are a lot less restrictive than GPL. As far as I understand it, GPL forces everything that uses it to also be GPL.

**Comment by SK83RJOSH** [comment]
Aye, I'm not a huge fan of GPL for that reason, but I think it's the right choice of license for a repo like this one. I might suggest adding a specific license exception for code derived from this repo, which would also protect users of the reference itself.

GCC [does this](https://www.gnu.org/licenses/gcc-exception-3.1.en.html), as well as [gnu bison](https://spdx.org/licenses/GPL-2.0-with-bison-exception.html). I would suggest @davidgfnet more or less lift the wording of the bison exception and append it to the existing license, allowing people to use this to do things such as compilers without worry. 🙂 

For the yaml itself, I think that perhaps that would be best unlicensed, since I presume it to be comprised of information from a lot of sources and as such the copyright might be a bit wishy washy to begin with (outside of the words David has added himself of course, in the way of descriptions and what not, as well as the general format).

Though I would say any permissive license, that requires the user to upstream improvements, may also be a good choice for the yaml such that folks at the very least contribute fixes.

**Comment by davidgfnet** [comment]
I was inspecting the contents of the repo and I think we could do:

 - psp-tests should be under GPL license, since it's a mixture of autogenerated code and manual code that's used for testing and nothing else. Again, don't expect these to ever be used in a game/lib. I will make an exception (MIT) for `psp-tests/manual/exception-module` since that code is very useful (perhaps I should also add a similar version to psp-samples repo) and shows how to capture exceptions, but also resume them (can be useful in an emulator/dynarec, for instance.
 - docs can also be GPL? It's documentation but mostly HTML and reference outputs. Seems GPL is "ok" for documentation too. Given that all doc claims are tested in psp-tests seems appropriate :)
 - "The YAML": I have no idea what kind of license this should be. The instruction encodings are not "mine" since I didn't invent them, I'm merely documenting them. They could even be patented for all we know (haven't checked). Some parts are my creation (like the pseudo/C code) while the encodings and names are not. Should we just release this under the public domain? To avoid any weird claims? Or something like MIT? Or just make an exception like bison saying that "using this YAML to produce other stuff is totally fine".
 - The python scripts (for autogeneration and YAML parsing): I think you do not use these right? Is this OK to be under the GPL? Their output is already under the GPL (for psp-tests). For instparse.py and reginfo.py I can see people using them to generate stuff, we could always release under the MIT license.

I'm really open when it comes to licensing, I'd just love for other projects to contribute back as much as they can if they ever use some of this. But I also want to give people the freedom to use this for literally anything :)

Thanks for bringing this up!

**Comment by SK83RJOSH** [comment]
> "The YAML": I have no idea what kind of license this should be. The instruction encodings are not "mine" since I didn't invent them, I'm merely documenting them. They could even be patented for all we know (haven't checked). Some parts are my creation (like the pseudo/C code) while the encodings and names are not. Should we just release this under the public domain? To avoid any weird claims? Or something like MIT? Or just make an exception like bison saying that "using this YAML to produce other stuff is totally fine".

Aye it's tricky, I would say it *might* be worth specifically not licensing that at all, perhaps with unlicense/public domain?

> The python scripts (for autogeneration and YAML parsing): I think you do not use these right?

Nope, I copied the yaml over to my test repo (without attribution, I'll fix that shortly) and just chew through you definitions. So all of your generation/output/everything else can be GPL 🙂

**Comment by davidgfnet** [comment]
Allrighty! I just updated this.
Lemme know if you are happy with it :)
I would also appreciate if you updated your YAML to match the new one, just to have the licensing clarified :)
Thanks for bringing this up, always happy to help other cool projects like PSP rust!

**Comment by SK83RJOSH** [comment]
You're the man, thank you so much 😄
